#!/usr/bin/env bash

os_name=$(uname)
if [[ $os_name == 'Darwin' ]];then
   dir=$(greadlink -f "$0")
else 
   dir=$(readlink -f "$0")
fi

### start ###
#dir=$(readlink -f "$0")
dir=$(dirname $dir)

perl -I$dir/local $dir/cg-compose.pl $@

