#!/usr/bin/env bash
usage() {
  echo "Usage: cg-cli crud one      <master>"
  echo "       cg-cli crud onemany  <master> <slave>"
  echo "       cg-cli crud manymany <master> <peer> <relation>"
  echo "       cg-cli crud group    <group>  [by]"
  echo "       cg-cli show tables"
  echo "       cg-cli show create table <table-name>"
  echo "       cg-cli gen  <table> [...]"
  echo "--"
  echo "   gen  ## gen with initialize=true"
}
usage_gen() {
   echo "Usage: cg-cli gen <table> ..."
}


cmd=$1
if [ ! $cmd ];then
   usage
   exit
fi

if [ "$cmd"x == "show"x ];then
   if [ "$2"x == "tables"x ];then
      cmd=showtables
   elif [ "$2"x == "create"x -a "$3"x == "table"x ];then
      if [ ! $4 ];then
         usage
         exit
      fi 
      cmd=showcreatetable
   fi
fi

if [ "$cmd"x == "gen"x ];then
   if [ ! $2 ];then
      usage_gen
      exit
   fi
   shift
fi

dir=$(dirname $0)

POM=code-generator-pom.xml
pom=$dir/$POM
pom_gen=$dir/gen/$POM

## get connection string
url=$(grep "<url>" $pom)
url=${url%</url>}
url=${url#*<url>}
url=${url//amp;/}
#echo $url

gen() {
   mvn -Dinit=true com.jfeat:sb-code-generator:1.2.3:generate -f $pom_gen
}

getdatabase(){
   #cut after ?
   db=$url
   db=${db##*/}
   db=${db%%[\?]*}
   echo $db
}

showtables() {
    db=$(getdatabase)
    sql="select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='$db' and TABLE_NAME <> 'schema_version'"
    for t in $($dir/mysql-test/bin/mysql-test "$url" "$sql");do
        echo $t
    done
}

#IFS=$'\n'
showcreatetable() {
    table=$1
    sql="show create table $table"
    result=$($dir/mysql-test/bin/mysql-test "$url" "$sql")
    echo $result
    #for l in $result;do
    #   echo $l
    #done
}

## test mysql
test_connection() {
   mysql_test=$($dir/mysql-test/bin/mysql-test $url "select now()")
   if [ "$mysql_test" ];then
      return 0
   else
      return 1
   fi
}

#test_connection

if [ $? -eq 0 ];then
  echo '' > /dev/null
else
  exit
fi

if [ "$cmd"x == "showtables"x ];then
   showtables
elif [ "$cmd"x == "showcreatetable"x ];then
   showcreatetable $4
elif [ "$cmd"x == "gen"x ];then
   # config tables
   $dir/conf-cli table add $@
   # gen persistance
   gen
fi

