#!/usr/bin/env bash
usage() {
  echo "Usage:"
  echo "    cg-cli [-h] [--help] [--gen]"
  echo "    cg-cli sanity"
  echo "    cg-cli show tables"
  echo "    cg-cli show create table <table-name>"
  echo "    cg-cli crud one      <master> [...]"
  echo "    cg-cli crud onemany  <master> <slave:mid> [...]"
  echo "    cg-cli crud manymany <master> <peer> <relation>"
  echo "    cg-cli crud group    <group> [groupBy] [groupId]"
  echo "    cg-cli initialize <table> [...]"
  echo "    cg-cli test run sql [/path/to/schema.sql]"
  echo "    cg-cli test crud one"
  echo "    cg-cli test crud onemany"
  echo "    cg-cli test crud manymany"
  echo "    cg-cli test crud group"
  echo "    cg-cli test crud groupby"
}

## start 
cmd=$1
gen='-'
if [ ! $cmd ];then
   usage
   exit
fi
for p in $@;do
   if [ "$p"x == "-h"x -o "$p"x == "--help"x ];then
      usage
      exit
   fi

   ## get check
   if [ "$p"x == "--gen"x ];then
      gen='--gen'
   fi
done

if [ "$cmd"x == "sanity"x ];then
   echo 'ok' > /dev/null

elif [ "$cmd"x == "show"x ];then
   if [ "$2"x == "tables"x ];then
      cmd=showtables

   elif [ "$2"x == "create"x -a "$3"x == "table"x ];then

      ## check usage
      if [ ! $4 ];then
         usage
         exit
      fi 
      ## end

      cmd=showcreatetable
   else
       usage
       exit
   fi

elif [ "$cmd"x == "crud"x ];then
   if [ "$2"x == "one"x ];then
      
      ## check usage
      if [ ! $3 ];then
         usage
         exit
      fi 
      ## end

      cmd=crudone

   elif [ "$2"x == "onemany"x ];then
      # $3-master; $4-slave:mid
     
      ## check usage
      if [ ! $4 ];then
         usage
         exit
      fi 
      ## end

      cmd=crudonemany

   elif [ "$2"x == "manymany"x ];then
       # $3-master; $4-peer, $5-relation

      ## check usage
      if [ ! $5 ];then
         usage
         exit
      fi 
      ## end

      cmd=crudmanymany
   
   elif [ "$2"x == "group"x ];then
       # $3-group; $4-groupBy $5-groupId

      ## check usage
      if [ ! $3 ];then
         usage
         exit
      fi
      ## groupBy must provide groupId
      if [ $4 ];then
         if [ ! $5 ];then
            usage
            exit
         fi
      fi
      ## end

      cmd=crudgroup
   fi

elif [ "$cmd"x == "initialize"x ];then
   if [ ! $2 ];then
      usage
      exit
   fi
elif [ "$cmd"x == "test"x ];then

   if [ "$2"x == "run"x ];then 
      if [ ! $3 ];then
         usage
         exit
      fi
      cmd=testrunsql

   elif [  "$2"x == "crud"x ];then 
       if [ "$3"x == "one"x ];then
           cmd=testcrudone
       elif [ "$3"x == "onemany"x ];then
           cmd=testcrudonemany
       elif [ "$3"x == "manymany"x ];then
           cmd=testcrudmanymany
       elif [ "$3"x == "group"x ];then
           cmd=testcrudgroup
       elif [ "$3"x == "groupby"x ];then
           cmd=testcrudgroupby
       else
         usage
         exit
       fi

   else
      usage
      exit
   fi
else
    usage
    exit
fi


### start ###

dir=$(dirname $0)
CONFCLI=$dir/local/conf-cli

POM=code-generator-pom.xml
pom=$dir/gen/$POM
if [ ! -e $pom ];then
   if [ ! -d $dir/gen ];then
       mkdir $dir/gen
   fi
   cp $dir/$POM $pom
fi

## get connection string
url=$(grep "<url>" $pom)
url=${url%</url>}
url=${url#*<url>}
url=${url//amp;/}
#echo $url

match_database(){
   #cut after ?
   db=$url
   db=${db##*/}
   db=${db%%[\?]*}
   echo $db
}

## sanity test for mysql
sanity() {
   mysql_test=$($dir/mysql-test/bin/mysql-test $url "select now()")
   if [ "$mysql_test" ];then
      echo "Connection to $url succeeded!"
   else
      exit
   fi
}

showtables() {
    db=$(match_database)
    sql="select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA='$db' and TABLE_NAME <> 'schema_version'"
    for t in $($dir/mysql-test/bin/mysql-test "$url" "$sql");do
        echo $t
    done
}

showcreatetable() {
    table=$1
    sql="show create table $table"
    result=$($dir/mysql-test/bin/mysql-test "$url" "$sql")
    #result="'tenant'|'CREATE TABLE \`tenant\` ( \`id\` bigint(20) NOT NULL, \`status\` int(11) DEFAULT NULL, \`name\` varchar(255) DEFAULT NULL, \`delete_flag\` int(11) NOT NULL DEFAULT '1', PRIMARY KEY (\`id\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8'"

    result=${result#*[|]}
    result=${result#*[\']}
    result=${result%[\']*}
    result=${result//,/,!}

    #result=${result#*[(]}
    #result=${result%[)]*}
    #arr=(${result//,/})
    #arr=($(echo "$result" | tr ',' '\n'))
    
    echo $result | tr '!' '\n'
}

initialize() {
   mvn -Dinit=true com.jfeat:sb-code-generator:1.3.0:generate -f $pom
}

gen() {
   if [ "$gen"x == "--gen"x ];then
      mvn com.jfeat:sb-code-generator:1.3.0:generate -f $pom
   fi
}

testinit(){
   ## copy default schema sql for crud test
   if [ ! -e $dir/src/main/resources/sql/cg-mysql-schema.sql ];then
      if [ ! -d $dir/src/main/resources/sql ];then
          mkdir -p $dir/src/main/resources/sql
      fi
      cp $dir/assets/src/main/resources/sql/cg-mysql-schema.sql src/main/resources/sql
   fi
   if [ ! -e $dir/src/main/java/com/jfeat/AmApplication.java ];then
      if [ ! -d $dir/src/main/java/com/jfeat ];then
          mkdir -p $dir/src/main/java/com/jfeat
      fi
      cp $dir/assets/src/main/java/com/jfeat/AmApplication.java src/main/java/com/jfeat
   fi
   if [ ! -e $dir/pom.xml ];then
      cp $dir/assets/pom.xml $dir
   fi

   if [ -d $dir/src/main/java/com/jfeat/am ];then
      rm -rf $dir/src/main/java/com/jfeat/am
   fi
}

### main ##

## check test init first
if [[ $cmd == test* ]];then
    testinit
fi

## check cmd and exec
if [ "$cmd"x == "sanity"x ];then
   sanity

elif [ "$cmd"x == "showtables"x ];then
   showtables

elif [ "$cmd"x == "showcreatetable"x ];then
   tab=$4
   showcreatetable $tab

elif [ "$cmd"x == "crudone"x -o "$cmd"x == "testcrudone"x ];then
   master=$3

   if [ "$cmd"x == "testcrudone"x ];then
      master='cg_master_resource'
   fi

   shift; ## shift crud
   shift; ## shift one

   for master in $@;do
 
      # config table
      $CONFCLI table reset --save
      $CONFCLI table add $master --save
      # config crud
      $CONFCLI crud reset --save
      $CONFCLI crud add one $master --save
      # config end

      $CONFCLI list -t -c
      ## gen crud
      gen

   done

elif [ "$cmd"x == "crudonemany"x ];then
   master=$3; 
   
   shift; ## shift cmd
   shift; ## shift onemany
   shift; ## shift master

   # config table
   $CONFCLI table reset --save
   $CONFCLI table add $master $@ --save

   # config crud
   $CONFCLI crud reset --save
   $CONFCLI crud add onemany $master $@ --save
   # config end

   $CONFCLI list -t -c
   ## gen crud
   gen
elif [ "$cmd"x == "testcrudonemany"x ];then
   master='cg_master_resource'
   slave='cg_master_resource_item:master_id'

   # config table
   $CONFCLI table reset --save
   $CONFCLI table add $master $slave --save

   # config crud
   $CONFCLI crud reset --save
   $CONFCLI crud add onemany $master $slave  --save
   # config end

   $CONFCLI list -t -c

   ## gen crud
   gen
    
elif [ "$cmd"x == "crudmanymany"x -o "$cmd"x == "testcrudmanymany"x ];then
   master=$3; 
   peer=$4; 
   relation=$5

   if [ "$cmd"x == "testcrudmanymany"x ];then
       master='cg_master_resource'
       peer='cg_master_resource_peer'
       relation='cg_master_resource_relation'
   fi

   # config table
   $CONFCLI table reset --save
   $CONFCLI table add $master $peer $relation --save
   # config crud
   $CONFCLI crud reset --save
   $CONFCLI crud add manymany $master $peer $relation --save
   # config end
   
   # show the result [-t - show tables] and  [-c - show cruds]
   $CONFCLI list -t -c

   ## gen crud
   gen

elif [ "$cmd"x == "crudgroup"x -o "$cmd"x == "testcrudgroup"x -o "$cmd"x == "testcrudgroupby"x ];then

   if [ "$cmd"x == "crudgroup"x ];then
      group=$3;

      ## 因maven插件限制，group 与  groupby 需要分两次测试
      if [ $4 ];then
         groupBy=$4;
         groupId=$5;

         cmd="crudgroupby"
      fi

   elif [ "$cmd"x == "testcrudgroup"x ];then
       group='cg_master_resource_category'

   elif [ "$cmd"x == "testcrudgroupby"x ];then
       group='cg_master_resource_category'
       groupBy='cg_master_resource'
       groupId='category_id'
   fi


   ## gen group first step

   if [ "$cmd"x == "crudgroup"x -o "$cmd"x == "crudgroupby"x -o "$cmd"x == "testcrudgroup"x ];then

      # config table
      $CONFCLI table reset --save
      $CONFCLI table add $group --save
      # config crud
      $CONFCLI crud reset --save
      $CONFCLI crud add group $group --save
      # config end

      $CONFCLI list -t -c
      ## gen crud
      gen
   fi


   ## gen groupby second step
   if [ "$cmd"x == "crudgroupby"x -o "$cmd"x == "testcrudgroupby"x ];then
       # config table
      $CONFCLI table reset --save
      $CONFCLI table add $groupBy --save
      # config crud
      $CONFCLI crud reset --save
      $CONFCLI crud add group $group $groupBy $groupId --save
      # config end

      $CONFCLI list -t -c
      ## gen crud
      gen
   fi


elif [ "$cmd"x == "initialize"x ];then
   # config tables
   $CONFCLI table reset --save
   $CONFCLI table add $@ --save

   # gen persistance
   initialize

elif [ "$cmd"x == "testrunsql"x ];then
    schemasql=$4

    ## if user schema sql, check exists
    if [ $schemasql ];then
       if [ ! -e  $schemasql ];then
           echo "schema sql $schemasql not found!"
           exit
       fi

       $dir/mysql-test/bin/mysql-test $url $schemasql
       exit  ## end
    fi

    ## run all sql files
    for sql in $(ls src/main/resources/sql/*.sql);do
       echo $sql
       $dir/mysql-test/bin/mysql-test $url $sql
    done

else
    usage
    exit
fi
