#!/usr/bin/env bash
usage() {
  echo "Usage:"
  echo "    cruds-cli [OPTIONS] -h --help --gen"
  echo "    cruds-cli show"
  echo "    cruds-cli add one <master> [...]"
  echo "    cruds-cli add onemany <master> --slave <slave> <mid> [wid] [...]"
  echo "    cruds-cli add manymany <master> <peer> <relation>"
  echo "    cruds-cli add group <group> [groupBy] [groupId]"
  echo "    cruds-cli run -f <crud-config>"
}

## start
cmd=$1
gen='-'
if [ ! $cmd ];then
   usage
   exit
fi
for p in $@;do
   if [ "$p"x == "-h"x -o "$p"x == "--help"x ];then
      usage
      exit
   fi

   ## get check
   if [ "$p"x == "--gen"x ];then
      gen='--gen'
   fi
done


if [ "$cmd"x == "cruds"x ];then
   ## cg-cli cruds dsl
   if [[ ! $2 == dsl ]];then
       usage_cruds
       exit
   fi

   subcmd=$3

   ## cg-cli cruds dsl show
   if [[ $subcmd == show ]];then
      cmd=crudsdslshow


   ## cg-cli cruds dsl add 
   elif [[ $subcmd == add ]];then
      subcmd=$4

      if [[ $subcmd == one ]];then
         if [ ! $5 ];then
            usage_cruds
            exit
         fi
         cmd=crudsdsladdone

      elif [[ $subcmd == onemany ]];then
         ## TODO, check --slave
         cmd=crudsdsladdonemany

      elif [[ $subcmd == manymany ]];then
         if [ ! $7 ];then
            usage_cruds
            exit
         fi
         cmd=crudsdsladdmanymany

      elif [[ $subcmd == group ]];then
         if [ ! $5 ];then
            usage_cruds
            exit
         fi
         cmd=crudsdsladdgroup

      else
          usage_cruds
          exit
      fi

   ## cg-cli cruds dsl run -f <crud-config>
   elif [[ $subcmd == run ]];then
      if [[ ! $4 == -f ]];then
         echo "    cg-cli cruds dsl run -f <crud-config>"
         exit
      fi
      if [ ! -e $5 ];then
         echo "    cg-cli cruds dsl run -f <crud-config>"
         echo fatal: cruds config file $3 not exists
         exit
      fi
      cmd=crudsdslrun

   else 
       usage_cruds
       exit
   fi
else
    usage
    exit
fi


### start ###
dir=$(readlink -f $0)
dir=$(dirname $dir)
CONFCLI="perl -I$dir/local $dir/local/conf-cli"

POM=code-generator-pom.xml
pom=gen/$POM
if [ ! -e $pom ];then
   if [ ! -d gen ];then
       mkdir gen
   fi
   cp $dir/assets/$POM $pom
fi

crudsdslshow() {
   echo
}

crudsdsladdone() {
   echo
}

crudsdsladdonemany() {
   echo
}

crudsdsladdmanymany() {
   echo
}

crudsdsladdgroup() {
   echo
}

crudsdslrun() {
   echo
}



gen() {
   if [ "$gen"x == "--gen"x ];then
      echo "mvn com.jfeat:sb-code-generator:1.3.1:generate -f $pom"
      mvn com.jfeat:sb-code-generator:1.3.1:generate -f $pom
   fi
}


### main ##
if [ "$cmd"x == "crudsdslshow"x ];then
    crudsdslshow

elif [ "$cmd"x == "crudsdsladdone"x ];then
    shift #shift cruds
    shift #shift dsl
    shift #shift add
    shift #shift one
    crudsdsladdone $@

elif [ "$cmd"x == "crudsdsladdonemany"x ];then
    shift #shift cruds
    shift #shift dsl
    shift #shift add
    shift #shift onemany
    crudsdsladdonemany $@

elif [ "$cmd"x == "crudsdsladdmanymany"x ];then
    shift #shift cruds
    shift #shift dsl
    shift #shift add
    shift #shift manymany
    crudsdsladdmanymany $@

elif [ "$cmd"x == "crudsdsladdgroup"x ];then
    shift #shift cruds
    shift #shift dsl
    shift #shift add
    shift #shift group
    crudsdsladdmanymany $@

elif [ "$cmd"x == "crudsdslrun"x ];then
    dsl=$5
    crudsdslrun $dsl

else
    usage
    exit
fi
